Update README.md
Attumm/redis-dict pull request #6
Opened 2020-09-13 13:08 UTC by Attumm

Updated Readme

2020-09-13 19:02 UTC, techhazard requested changes
Hi @Attumm,

I've found redis-dict very helpful so far, so I thought I'd contribute a little.

I made some suggestions regarding your new documentation. I hope you can appreciate them.

2020-09-13 19:02 UTC, techhazard commented on README.md
>  This project is used in different companies in production.
Suggestion:

> This project is used by different companies in production.

2020-09-14 17:52 UTC, Attumm commented
Thanks @techhazard, great suggestions.

2020-09-14 17:52 UTC, merged

2020-09-14 17:53 UTC, Attumm reviewed
thanks to @techhazard

2020-09-29 15:25 UTC, techhazard commented
You're welcome, @Attumm :smiley: